### ISSUE TITLE
confusion

### ISSUE THREAD

**Issue by H-ishak** [gennadiygnezdilov/php-ocpp-1.6J#1]
what is the point of creating a public repository to do something and not giving the core features ??
does this repository work ?

**Comment by gennadiygnezdilov** [comment]
My repository is made for commerce. The script works well. Constantly updated, who bought the script from me, always provide technical support

**Comment by gennadiygnezdilov** [comment]
> what is the point of creating a public repository to do something and not giving the core features ?? does this repository work ?

My repository is made for commerce. The script works well. Constantly updated, who bought the script from me, always provide technical support

**Comment by H-ishak** [comment]
@gennadiygnezdilov thanks for the explanation . Gl next
